### ISSUE TITLE
Titanium SDK 6 compatibility?

### ISSUE THREAD

**Issue by Astrovic** [dbankier/TiShadow#511]
I'm testing the new Titanium SDK 6 RC version, but can't use tishadow because receive this error:

`[ERROR] ** BUILD FAILED **`
`[ERROR] The following build commands failed:`
`[ERROR]         CompileC build/Intermediates/TestApp.build/Debug-iphoneos/TestApp.build/Objects-normal/armv7/TiUIRefreshControlProxy.o Classes/TiUIRefreshControlProxy.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler`
`[ERROR] (1 failure)`

**Comment by yomybaby** [comment]
iOS only?

**Comment by Astrovic** [comment]
On android I've this error:

`[WARN]  Could not find a valid Titanium module id=net.iamyellow.tiws version=1.0.0 platform=android deploy-type=development`
`[WARN]  Could not find a valid Titanium module id=yy.logcatcher version=0.1 platform=android deploy-type=development`
`[WARN]  Could not find a valid Titanium module id=ti.compression version=2.0.4 platform=android deploy-type=development`
`[WARN]  Could not find a valid Titanium module id=bencoding.android.tools version=latest platform=android deploy-type=development`
`[ERROR] Found incompatible Titanium Modules:`
`[ERROR]    id: net.iamyellow.tiws	 version: 1.0.0	 platform: android	 min sdk: 3.5.1.GA`
`[ERROR]    id: yy.logcatcher	 version: 0.1	 platform: android	 min sdk: 3.2.2.GA`
`[ERROR]    id: ti.compression	 version: 2.0.4	 platform: android	 min sdk: 3.2.2.GA`
`[ERROR]    id: ti.compression	 version: 2.0.4	 platform: android	 min sdk: 3.2.2.GA`
`[ERROR]    id: bencoding.android.tools	 version: 0.34	 platform: android	 min sdk: 3.2.0.GA`
`[ERROR]    id: bencoding.android.tools	 version: 0.40	 platform: android	 min sdk: 5.1.0.GA`

But this happens because the Android modules used are not yet compatible with Titanium 6

**Comment by dbankier** [comment]
Yep. But, I'll wait till it is GA...

**Comment by hansemannn** [comment]
@Astrovic This rather looks like a SDK compile-issue. Can you paste me the whole trace-log in Slack?

**Comment by Astrovic** [comment]
Hi @hansemannn 
I had this error on TiSDK 6.0.0 RC (6.0.0.v20161101155110) and Appcelerator CLI 4.2.8-9 (https://www.appcelerator.com/blog/2016/11/rc-releases-for-6-0-0-of-sdk-cli-4-8-0-of-studio/).
Now I restored the stable version (SDK 5.5.1.GA and APPC CLI 4.2.7) because I have to develop some updates in several of my projects, so I can not test it again at the moment :(

**Comment by hansemannn** [comment]
@Astrovic We just released 6.0.0.GA yesterday. Would be cool if you could file an issue with some demo-code around it so we can check it (if it's an SDK issue). Thx!

**Comment by Astrovic** [comment]
@hansemannn I just did a test with the new SDK 6.0.0.GA, and the problem persists if I build on my device (**iPhone 5S, iOS 10.1**).

I just create a new project:

1.  `appc new`
2.  ❯ `Native App (app) `
3.  ❯ `Titanium SDK (JavaScript)`

I choose the name, and then

`appc ti build -p iphone -T device -l trace --shadow`

but I receive this error:
```
[ERROR] ** BUILD FAILED **
[ERROR] The following build commands failed:
[ERROR]         CompileC build/Intermediates/myNewApp.build/Debug-iphoneos/myNewApp.build/Objects-normal/armv7/TiUIRefreshControlProxy.o Classes/TiUIRefreshControlProxy.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
[ERROR] (1 failure)
```

Instead it work if I use the iOS simulator:
`appc ti build -p iphone -l trace --shadow`

--
Then on https://github.com/dbankier/TiShadow/blob/master/app/Resources/api/Includes.js it would be necessary to update the API, for example, replace those `Titanium.UI.iPhone` with the new `Titanium.UI.iOS`

--
And android modules https://github.com/dbankier/TiShadow/tree/master/app/modules/android should be updated at the last apiversion 3 to be compatible with SDK 6.0.0.GA

**Comment by hansemannn** [comment]
That's correct. But for me, the SDK-issue is most important right now. Does it work without TiShadow? If it does, it's also a TiShadow issue, otherwise the Titanium SDK needs to be fixed.

**Comment by Astrovic** [comment]
sure, it work without TiShadow, otherwise I would have reported the bug on jira ;)

**Comment by gimdongwoo** [comment]
Ti SDK 6.0.0+ need to android modules rebuild.
https://wiki.appcelerator.org/display/guides2/Titanium+SDK+6.0.0+Changes

If you want to rebuild this modules, I try to rebuild.
I'm already some modules rebuilding for my project.

[ERROR] Found incompatible Titanium Modules:
[ERROR]    id: net.iamyellow.tiws	 version: 1.0.0	 platform: android	 min sdk: 3.5.1.GA
[ERROR]    id: yy.logcatcher	 version: 0.1	 platform: android	 min sdk: 3.2.2.GA
[ERROR]    id: ti.compression	 version: 2.0.4	 platform: android	 min sdk: 3.2.2.GA
[ERROR]    id: bencoding.android.tools	 version: 0.34	 platform: android	 min sdk: 3.2.0.GA

**Comment by gimdongwoo** [comment]
I did building modules all needed to tishadow.
https://github.com/gimdongwoo

**Comment by gimdongwoo** [comment]
Appified application build and run successful.
But, application have many problems.

https://github.com/gimdongwoo/TiShadow/tree/TiSDK6.0.0%2B

**Comment by Astrovic** [comment]
Awesome job @gimdongwoo! What is the problem with i18n?

**Comment by gimdongwoo** [comment]
@Agnostic It didn't work i18n feature.

**Comment by Agnostic** [comment]
@Astrovic ^ 😄

**Comment by Astrovic** [comment]
@gimdongwoo  you should bump package version https://github.com/gimdongwoo/TiShadow/blob/TiSDK6.0.0%2B/package.json to 2.8.10 👍

**Comment by dbankier** [comment]
thanks for the PR @gimdongwoo, I'll get on to it soon

**Comment by dbankier** [comment]
i18n features is working fine - you can try with a classic project.
eg: `ts run -u -l es`

The new alloy way requires you to run alloy compile to move the i18n files to the correct directory. TBH that is a pain.
The PR was merged  - thanks to the efforts of @gimdongwoo.
I also just tested on  iOS using a basic project and it is working on 6.0.0

I will push to npm soon after a bit of cleaning up...

**Comment by mrtomnguyen** [comment]
@Astrovic hey im having the same issue. did you ever figure it out?
i dont think it's any of the modules.

SDK 6.0.0 and SDK 6.0.1
Xcode 8
Device ios 10.2.1

**Comment by mrtomnguyen** [comment]
i think i've narrowed it down to this api being broken.
Ti.UI.createRefreshControl

**Comment by dbankier** [comment]
it should work. can you do a clean build

**Comment by DaKaZ** [comment]
I just wanted to chime in and say thank you.  You don't know how much better ti.shadow makes my life, and I greatly appreciate all of your efforts :)
